### PR TITLE
Updated Anno 1800 IDs

### PR DESCRIPTION
**Pull request by asqwedd**
Added Anno 1800 ID:
      60682 //Anno 1800 DLC - Sesional Decorations (CDLC07)

Removed Anno 1800 IDs that don't exist in game files:
      12176,
      59682,

### CODE REVIEW

**Comment by acidicoala** [comment]
Thanks for the new DLC ID. The DLC IDs `12176` & `59682` are present in every DLC request made by game as can be seen in the log from this post: https://cs.rin.ru/forum/viewtopic.php?p=2537054#p2537054

We may not know what those IDs correspond to, but I don't see harm in including valid IDs. In fact, in most of R2 games many of the valid IDs remain unknown.

P.S. Could you please fix a typo in "Seasonal Decorations" comment?

**Comment by asqwedd** [comment]
With every other ID we can look in the data files and see what exactly each one if them unlocks. There is probably no harm in having these extra IDs included but I don't see a reason TO include them since the list without these IDs already unlocks everything in the game. So that is why my vote is we take them out. But at the end of the day this is your repo and it's up to you if you want to include these IDs or not.

And it's not my typo to fix. That text is copied directly from the game data file same as the rest of the comments.

**Comment by acidicoala** [comment]
2 reasons to include DLC IDs:
- This is a general list of all publicly known Product IDs that are used by UPC R2 in one way or another. DLC Unlocker just happens to be one of its usages.
- It makes it easier for people to spot new DLC IDs in their log files.

If you find out the purpose of these unknown IDs, and they turn out to be potentially disruptive (like *free weekend* items) then we can comment them out like we did with others.

___

Regarding the typo: it is a sub-optimal choice to rely on game assets for naming in comments, because:
- Asset names can and often do differ from the store names (see *BL3* for example), and it is more intuitive to search for the store name, rather than asset name.
- We can't know asset names for all DLCs, but we can know their store names. Mixing both will lead to inconsistencies, hence it is better to use store names exclusively.

**Comment by Christsnatcher** [comment]
Just chiming in to let you know that I consider both points @acidicoala stated valid arguments, and due to this vote for keeping "invalid" DLC IDs in our list and solely use store names in comments, instead of names retrieved from game data.

**Comment by asqwedd** [comment]
I thought my previous commit was the right way to go, but you two are in charge here and I'm not going to try and change your mind.
Hope the new proposed change is to your liking.

**Comment by acidicoala** [comment]
Thank you for contribution!

**Pull request merged**
